#ifndef LOGINWINDOW_H
#define LOGINWINDOW_H

#include <QMainWindow>
#include <QStackedWidget>

QT_BEGIN_NAMESPACE
namespace Ui { class LoginWindow; }  // generated by QT, the forward declaration for the UI class
QT_END_NAMESPACE

/**
 * @author Kevin Liu
 * @brief Loginwindow class for the application
 * @details can be found in the .cpp file for this function as well as the following ones.
 */
class LoginWindow : public QMainWindow
{
    Q_OBJECT

public:
    /**
     * @brief sets up the Login Window
     * @param parent optional parent widget
     */
    explicit LoginWindow(QWidget *parent = nullptr);

    /**
     * @brief cleans up ui stuff
     */
    ~LoginWindow();

signals:
    void loginSuccessful();

private slots:
    /**
     * @brief handles login button click
     */
    void on_loginButton_clicked();

    /**
     * @brief switches to forgot password page
     */
    void on_forgotButton_clicked();

    /**
     * @brief switches to help page
     */
    void on_helpButton_clicked();

    /**
     * @brief goes back to main page
     */
    void on_backButton_2_clicked();

    /**
     * @brief goes back to main page
     */
    void on_backButton_clicked();

    /**
     * @brief goes back to main page
     */
    void on_backButton_3_clicked();

    /**
     * @brief handles password retrieval
     */
    void on_retrieveButton_clicked();

    /**
    * @brief signs up user and switches to main window
    */
    void on_signupButton_clicked();

    /**
    * @brief signs up user and switches to main window
    */
    void on_signupPageButton_clicked();

    /**
    * @brief goes back to main page from signup page
    */
    void on_backButton_7_clicked();


private:
    Ui::LoginWindow *ui; ///< pointer to UI components that are generated
    QStackedWidget *stackedWidget;///< widget that manages pages, such as login, signup, recover password, and help
};

#endif // LOGINWINDOW_H
